version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - skynet
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  adminer:
    image: adminer
    restart: "no"
    networks:
      - skynet
    ports:
      - ${ADMINER_HOST_PORT}:8080
    
networks:
  skynet:
